---
title: "Resolução de Sistema de Equações Lineares com R"
author: 
  - Theo Antunes^[IPEA, [theosantunes@gmail.com.](mailto:theosantunes@gmail.com )]
  - Rafael de Acypreste^[FACE - UnB, [rafaeldeacyprestemr@gmail.com](mailto:rafaeldeacyprestemr@gmail.com).]
date: "`r format(Sys.Date(),'%d/%m/%Y')`"
output: 
  beamer_presentation:
    theme: "Frankfurt"
    colortheme: "dove"
    toc: true
fontsize: "12pt"
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,warning = FALSE,echo = TRUE,fig.cap='Elaboração própria.')
```

# Test 

## R Markdown

A equação homogênea é indicada pela forma a seguir, em que $y_t$ é uma variável em função do tempo:

\begin{equation}
 y_{t+1} + ay_{t} = 0 
\end{equation} que pode ser resolvida conhecendo-se o valor inicial $y_0$. Assim, temos:

## Slide with Bullets

> - Bullet 1
> - Bullet 2
> - Bullet 3

## Slide with Bullets

<div class="red2">
This text is red
</div>

## Slide with R Output

```{r cars, echo = TRUE}
summary(cars)
```

---

```{r, echo=FALSE}
library(tidyverse)
a <- c(1.5,-1.5,0.5,-0.5,1,-1) # constantes
b <- 10
y_0 <- 0.2                 # condição inicial
y <- tibble("a=1.5, b=10" = rep(0,25),"a=-1.5, b=10" = rep(0,25),
            "a=0.5, b=10" = rep(0,25),"a=-0.5, b=10" = rep(0,25),
            "a=1, b=10" = rep(0,25),"a=-1, b=10" = rep(0,25),
            t = 1:25)

for (i in 1:5){
  for(t in 1:25){ 
    y[t,i] <- (-a[i])^t*y_0 + b/(1+a[i])
  }
}  

for(t in 1:25){ 
  y[t,6] <- (-a[i])^t*y_0 + b*t
  }

y %>% 
  pivot_longer(cols = 1:6,
               names_to="funcao",
               values_to = "values") %>% 
  ggplot(aes(x = t, y = values))+
  facet_wrap(vars(factor(funcao,levels = unique(funcao))),scales = "free",ncol=2)+
  geom_line(color = "red")+
  geom_point(alpha = .7,size=.5,color = "red")+
  labs(y = NULL)+
  theme_bw()

```


